# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackerNews Articles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackerNews Articles
  pod 'RealmSwift'
  pod 'SwipeCellKit'

end
